name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      
      - name: Enhanced Debug
        run: |
          echo "Current directory: $(pwd)"
          echo "Repository contents:"
          ls -la
          echo "Package files:"
          find . -name "package*.json" -type f
          echo "Lock files:"
          find . -name "*.lock" -type f
          echo "Git status:"
          git status
          echo "Git log (recent commits):"
          git log --oneline -n 5
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          # Disable caching completely
      
      - name: Install dependencies
        run: |
          # Force clean install without using lock file
          rm -f package-lock.json
          npm install
      
      - name: Run linting
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      
      - name: Enhanced Debug
        run: |
          echo "Current directory: $(pwd)"
          echo "Repository contents:"
          ls -la
          echo "Package files:"
          find . -name "package*.json" -type f
          echo "Lock files:"
          find . -name "*.lock" -type f
          echo "Git status:"
          git status
          echo "Git log (recent commits):"
          git log --oneline -n 5
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          # Disable caching completely
      
      - name: Install dependencies
        run: |
          # Force clean install without using lock file
          rm -f package-lock.json
          npm install
      
      - name: Run tests
        run: npm test