name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  dummy-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      
      - name: Repository Debug
        run: |
          echo "Current directory: $(pwd)"
          echo "Repository contents:"
          ls -la
          echo "GitHub Actions runner info:"
          env | grep GITHUB
      
      - name: Dummy Lint Check
        run: |
          echo "✅ Lint checks passed (dummy test)"
          # Create a dummy lint report
          mkdir -p reports
          echo "No lint errors found" > reports/lint-report.txt
      
      - name: Dummy Tests
        run: |
          echo "✅ Tests passed (dummy test)"
          # Create a dummy test report
          mkdir -p reports
          echo "All tests passed" > reports/test-report.txt
      
      - name: Upload Reports
        uses: actions/upload-artifact@v3
        with:
          name: dummy-reports
          path: reports/