name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      
      - name: Enhanced Debug
        run: |
          echo "Current directory: $(pwd)"
          echo "Repository contents:"
          ls -la
          echo "Package files:"
          find . -name "package*.json" -type f
          echo "Lock files:"
          find . -name "*.lock" -type f
          echo "Git status:"
          git status
          echo "Git log (recent commits):"
          git log --oneline -n 5
      
      - name: Manual Node.js Setup
        run: |
          echo "Using system Node.js instead of actions/setup-node"
          node --version
          npm --version
      
      - name: Install dependencies
        run: |
          echo "Environment debug: Locating package-lock.json"
          if [ -f package-lock.json ]; then
            echo "package-lock.json found:" 
            head -n 20 package-lock.json
          else
            echo "Error: package-lock.json not found!"
          fi
          npm ci
      
      - name: Run linting
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      
      - name: Enhanced Debug
        run: |
          echo "Current directory: $(pwd)"
          echo "Repository contents:"
          ls -la
          echo "Package files:"
          find . -name "package*.json" -type f
          echo "Lock files:"
          find . -name "*.lock" -type f
          echo "Git status:"
          git status
          echo "Git log (recent commits):"
          git log --oneline -n 5
      
      - name: Manual Node.js Setup
        run: |
          echo "Using system Node.js instead of actions/setup-node"
          node --version
          npm --version
      
      - name: Install dependencies
        run: |
          echo "Environment debug: Locating package-lock.json"
          if [ -f package-lock.json ]; then
            echo "package-lock.json found:" 
            head -n 20 package-lock.json
          else
            echo "Error: package-lock.json not found!"
          fi
          npm ci
      
      - name: Run tests
        run: npm test